name: ink_front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  go_router: ^16.3.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.0
  equatable: ^2.0.7
  cloud_functions: ^6.0.4
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Megabyte
      fonts:
        - asset: assets/fonts/MegabyteBlack.otf
          weight: 900
        - asset: assets/fonts/MegabyteBlackItalic.otf
          weight: 900
          style: italic

        - asset: assets/fonts/MegabyteBold.otf
          weight: 700
        - asset: assets/fonts/MegabyteBoldItalic.otf
          weight: 700
          style: italic

        - asset: assets/fonts/MegabyteMedium.otf
          weight: 500
        - asset: assets/fonts/MegabyteMediumItalic.otf
          weight: 500
          style: italic

        - asset: assets/fonts/MegabyteRegular.otf
          weight: 400
        - asset: assets/fonts/MegabyteRegularItalic.otf
          weight: 400
          style: italic

        - asset: assets/fonts/MegabyteLight.otf
          weight: 300
        - asset: assets/fonts/MegabyteLightItalic.otf
          weight: 300
          style: italic
